### ISSUE TITLE
File Tree has no subfolder indentation

### ISSUE THREAD

**Issue by Bestulo** [elitistsnob/typora-cobalt-theme#1]
In my main directory, I have up to 4 levels of subfolders. However, it's impossible to differentiate which folders are inside what folders except for the small turned triangle. This makes it impossible for me to use this theme because I have dozens of folders and hundreds of files and the only way to know which one I should choose is by looking at what branch they're in.

Below, I attach a screenshot of a test file directory with the Newsprint theme, then a screenshot using the Cobalt theme.

A secondary, less important issue is that the size of each item in the file tree is enormous. Having hundreds of texts to sift through, it's a bit hard with Cobalt, to say the least.

![image](https://user-images.githubusercontent.com/23301025/75619431-f343b200-5b51-11ea-902d-fc601fb40e0c.png)

![image](https://user-images.githubusercontent.com/23301025/75619369-626cd680-5b51-11ea-93df-4227d30cd98b.png)

**Comment by elitistsnob** [comment]
Thanks for reporting this issue. I will look into the problem.

**Comment by kinoute** [comment]
Any news on this? This is a truly great theme, but this problem is kind of disturbing. Thanks!

**Comment by matt0x6F** [comment]
> Thanks for reporting this issue. I will look into the problem.

If you can give me some direction then I'll fix this. I love this theme, but they're right, using this in FileTree view is a pain.

**Comment by kinoute** [comment]
I'm making my own fork of this awesome theme (full credits to @elitistsnob of course) because I couldn't use this sidebar as well:

It's not done yet completely but usable on macOS:

![Capture d’écran 2020-06-02 à 09 36 45](https://user-images.githubusercontent.com/623763/83671079-638c2480-a5d4-11ea-95e2-9cda905ad931.png)

https://github.com/kinoute/typora-hivacruz-theme

**Comment by Keith-Maxwell** [comment]
Hi ! Any news on this issue ? 
If this can be fixed, it will be the best theme for Typora, but currently it is hard to use...
Thanks

**Comment by elitistsnob** [comment]
Just pushed up a fix for this. Enjoy!

**Comment by elitistsnob** [comment]
Also just posted another update to this issue, and added folder icons! Get excited!

<img width="438" alt="Screen Shot 2020-10-08 at 3 15 57 PM" src="https://user-images.githubusercontent.com/538261/95504456-c0308f00-097a-11eb-9e4c-c8292caa1924.png">
