### ISSUE TITLE
Problem with line numbers for code block

### ISSUE THREAD

**Issue by lenzfilipski** [elitistsnob/typora-cobalt-theme#2]
The line number from the code block doesn't display correctly.
![Screenshot_20200303_002709](https://user-images.githubusercontent.com/29278669/75727793-2323be80-5ce6-11ea-9447-f7e2c9e796de.png)

**Comment by lenzfilipski** [comment]
I think it looks more like the cobalt theme without the box
![Screenshot_20200303_012544](https://user-images.githubusercontent.com/29278669/75730715-ec51a680-5ced-11ea-8da1-b20236d2405c.png)

**Comment by elitistsnob** [comment]
Thanks for reporting this issue. I will be releasing an update to address this and another reported issue soon.

**Comment by Jacob-pixil** [comment]
this sure is a problem for me. please fix it. and by the way, really enjoy your theme.

**Comment by tpcmi** [comment]
waiting........
 ：）

**Comment by elitistsnob** [comment]
Fixed.

**Comment by Jacob-pixil** [comment]
<img width="36" alt="屏幕快照 2020-03-20 上午1 49 57" src="https://user-images.githubusercontent.com/61943951/77098376-3b693c80-6a4d-11ea-9f14-32ad714b21a3.png">

thanks for the fix, but when it comes to line 100 and more, numbers start to be squashed up

**Comment by Jacob-pixil** [comment]
@elitistsnob

**Comment by elitistsnob** [comment]
Fixed.
